### ISSUE TITLE
Improve the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m2-evaluacion-intermedia-ifuenteromero#1]
Awesome work @ifuenteromero !!!

Here you have some tips to improve the exercise:

- [x] You don't need to nest a second if/else, just continue working with the first one.
- [x] Improve the organization of constants and variables, may be grouped by type?
- [x] Move the feedback logic to a function an execute it on each click
- [x] Move you counter logic into a function and execute it on each click
- [x] You are writing many times "helpEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into "helpEl"?
- [x] When the user clicks the button you are resetting the input number. Have in mind this makes the game more complex since the user lost reference of what just wrote. If it is to allow the user write in the input without having to erase, maybe you can write the number on the feedback, something like --> '54 es demasiado alto, prueba otra vez'. If you are making it on purpose to add complexity,  then when the random number is found I would leave it on the input or somewhere else.
- [x] **Indent and avoid extra white spaces to improve readability and prevent bugs**
- [x] Remove comments

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting the enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by ifuenteromero** [comment]
@nasivuela  I think it's done.

**Comment by ifuenteromero** [comment]
@nasivuela I think it's done. Thanks for your time :)

**Comment by nasivuela** [comment]
Omg!! Such good work!!

PD. Do not forget to indent to make it cleaner!

![](https://media.giphy.com/media/l0MYODGpFv9KRyCBO/giphy.gif)
